[[language]]
name = "rust"
auto-format = true
formatter = { command = "cargo fmt" }

[language-server.rust-analyzer.config]
check.command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"

# Notes stuff
# Markdown Oxide is a obisidan like lsp
# harper is for spellcheck

[[language]]
name = "markdown"
soft-wrap.enable = true
text-width = 80
soft-wrap.wrap-at-text-width = true
language-servers = ["markdown-oxide", "harper-ls"]

# WebDev shit

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "ts"] }
auto-format = true


[[language]]
name = "tsx"
language-servers = ["typescript-language-server"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "tsx"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "js"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = ["typescript-language-server"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "jsx"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = "dprint", args = ["fmt", "--stdin", "json"] }
auto-format = true

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "html"
language-servers = ["vscode-html-language-server"]
formatter = { command = 'dprint', args = ["fmt", "--stdin", "html"] }
auto-format = true

[[language]]
name = "css"
language-servers = ["vscode-css-language-server"]
formatter = { command = 'dprint', args = ["fmt", "--stdin", "css"] }
auto-format = true
