[[language]]
name="rust"
auto-format = true
formatter = { command = "cargo fmt" }

[language-server.rust-analyzer.config]
check.command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"
